logging:
  level:
    root: info
    com.lsy.sample: debug

spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
# 강의에 나온 dialect는 아래 였지만 저건 없어진 듯
#        dialect: org.hibernate.dialect.MYSQL5InnoDBDialect
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3307/metadb?serverTimezone=Asia/Seoul
    username: batch
    password: batch

  batch:
    job:
      names: ${job.name:NONE}