spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
# ???? ??? ????? ?? ??? ?
#        dialect: org.hibernate.dialect.MYSQL5InnoDBDialect
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/metadb?serverTimezone=Asia/Seoul
    username: batch
    password: batch